pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                nodejs('node-v17.9.0') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
    }
}